@php
    $refNumber = strtoupper($docCode ?? 'RPT') . '/' . now()->format('Y') . '/' . now()->format('md-His');
    $generatedBy = auth()->user()->name ?? 'System';
@endphp
<table class="letterhead-table">
    <tr>
        <td class="lh-emblem"><div class="emblem">AYS</div></td>
        <td class="lh-org">
            <div class="org-name">AYS GROUP</div>
            <div class="org-sub">Call Center &amp; Human Resource Management System</div>
        </td>
        <td class="lh-refbox">
            <div class="ref-label">Reference No.</div>
            <div class="ref-value">{{ $refNumber }}</div>
        </td>
    </tr>
</table>
<div class="lh-divider"></div>
<div class="doc-title-block">
    <h1 class="doc-title">{{ strtoupper($title) }}</h1>
    @if(!empty($subtitle))
        <p class="doc-subtitle">{{ $subtitle }}</p>
    @endif
</div>
<table class="meta-table">
    <tr>
        <td><span class="meta-label">Generated On</span><br><span class="meta-value">{{ now()->format('d F Y, H:i') }}</span></td>
        <td><span class="meta-label">Generated By</span><br><span class="meta-value">{{ $generatedBy }}</span></td>
        <td><span class="meta-label">Classification</span><br><span class="meta-value classification">Internal Use Only</span></td>
    </tr>
</table>
